name: Windows

on:
  push:
    branches:
      - '**'
  pull_request:
    branches:
      - '**'

jobs:
  build:
    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v3

    - name: Cache Boost
      id: cache-boost
      uses: actions/cache@v3
      with:
        path: ${{runner.temp}}\boost_1_88_0
        key: cache-boost

    - name: Get Boost
      if: steps.cache-boost.outputs.cache-hit != 'true'
      working-directory: ${{runner.temp}}
      shell: powershell
      run: |
        # Download Boost.
        Invoke-WebRequest `
            -Uri "https://archives.boost.io/release/1.88.0/source/boost_1_88_0.7z" `
            -OutFile boost.7z
        # Extract.
        7z x boost.7z
        # Build.
        cd boost_1_88_0
        .\bootstrap
        .\b2 link=static

    - name: Install pyOpenSSL
      working-directory: ${{runner.temp}}
      shell: powershell
      run: pip3 install pyOpenSSL

    - name: Build
      env:
        BOOST_ROOT: ${{runner.temp}}\boost_1_88_0
        Boost_INCLUDE_DIR: ${{runner.temp}}\boost_1_88_0\libs\headers
      shell: powershell
      run: |
        mkdir -p build
        cmake -S . -B build -DBoost_USE_STATIC_LIBS=ON -DBoost_DIR="$env:BOOST_ROOT\stage\lib\cmake\Boost-1.88.0"
        cmake --build build --config Release

    - name: Test libftp
      env:
        LIBFTP_TEST_SERVER_PATH: ${{github.workspace}}\test\server\server.py
      working-directory: ${{github.workspace}}\build\test\Release
      run: .\ftp_tests.exe

    - name: Test cmdline
      working-directory: ${{github.workspace}}\build\app\cmdline\test\Release
      run: .\cmdline_tests.exe
